### ISSUE TITLE
auth feedback

### ISSUE THREAD

**Issue by absterr08** [trevorzs/CryptoNight#1]
Great work so far! A few things I noticed:
- it doesnt seem like i can actually log in with my email, so the login form should either remove that wording or you can go ahead and implement that functionality.
- i can log in/log out just fine, but immediately after signing up I can't log out (i have to refresh after clicking the logout button to be logged out)

**Comment by trevorzs** [comment]
Thanks Abby! I didn't catch those. I've fixed them and reuploaded to Heroku :)
